# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Spring Configuration
spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:eexdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# Server Configuration
server:
  port: 8080 