id: 'lack_of_automation'
name: 'Lack of Automation'
description: 'Manual steps hamper faster development and increase failure risk.'
metrics_impacted:
  - 'deployment_frequency'
  - 'lead_time_for_changes'
  - 'change_failure_rate'
remediation_actions:
  - 'implement_ci'
  - 'adopt_trunk_based_development'