id: 'deployment_risk'
name: 'Deployment Risk'
description: 'Risk associated with deploying changes to production, including potential service disruptions and rollback challenges.'
metrics_impacted:
  - 'change_failure_rate'
  - 'mean_time_to_restore'
  - 'deployment_frequency'
remediation_actions:
  - 'implement_feature_flags'
  - 'implement_chaos_engineering'
  - 'automate_common_tasks'
  - 'improve_test_coverage' 