id: 'improve_development_environment'
name: 'Improve Development Environment'
description: 'Enhance local development setup with better IDE configurations, containerization, and development tools to reduce friction in daily work.' 