id: 'development_environment_issues'
name: 'Development Environment Issues'
description: 'Problems with local development environments, tooling, and infrastructure that impede developer productivity and flow'
type: 'developer'
impact_areas:
  - 'Developer productivity'
  - 'Code quality'
  - 'Local testing'
  - 'Development speed'
remediation_categories:
  - 'Environment standardization'
  - 'Development tools optimization'
  - 'Infrastructure automation'
  - 'Developer experience improvement' 